### ISSUE TITLE
Excellent repo, but too slow to compressing many images

### ISSUE THREAD

**Issue by anthonyweidai** [chenzhutian/hexo-all-minifier#106]
I am using your repo for hexo + githubpage. Your repo is very cool since it helps us open website pages faster. However, the big problem is that it compresses every image in every hexo g. 
When I have considerable number of images, it would be a disaster (too slow). Hope you can enhance it by **ignoring those images had been compressed before** in each hexo g.

**Comment by chenzhutian** [comment]
Good suggestion. I guess the only way to do this is to cache which pictures had been compressed. But this wont be easy since the program never know how long the cache should be renewed.
Another way is to exclude some images by using a glob.
I will see what I can do.

PR/suggestions are welcome.

**Comment by Davidietop** [comment]
Thanks for your answer.
