### ISSUE TITLE
npm WARN deprecated

### ISSUE THREAD

**Issue by zpcol** [chenzhutian/hexo-all-minifier#108]
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

**Comment by chenzhutian** [comment]
update:
https://github.com/chenzhutian/hexo-all-minifier/commit/62dc5010dd756b0fa3bcf198055c994bb8b05aab
