### ISSUE TITLE
throws no submodule mapping found error when npm install

### ISSUE THREAD

**Issue by mamboer** [chenzhutian/hexo-all-minifier#12]
it throws errors when installing it.

```
npm ERR! git submodule -q update --init --recursive: fatal: no submodule mapping found in .gitmodules for path 'test/testSite'
```

pls help, i'm going to fork your project and add some cool features.

**Comment by mamboer** [comment]
@unhealthy Maybe you miss the `.gitmodules` file in the root of the project

**Comment by chenzhutian** [comment]
close because inactive
