### ISSUE TITLE
html缩进没了

### ISSUE THREAD

**Issue by ehlxr** [chenzhutian/hexo-all-minifier#15]
压缩之前是有缩进的（输入法全拼模式下按tab缩进）
![image](https://cloud.githubusercontent.com/assets/11313370/18225814/871aecc4-722f-11e6-9e74-215acf74c628.png)
压缩后没了
![image](https://cloud.githubusercontent.com/assets/11313370/18225822/c8d41c58-722f-11e6-856b-b298a64572bd.png)

**Comment by chenzhutian** [comment]
这个估计是会把所有空格都压缩掉（包括tab和space）。
你想保留空格缩进的话可以用 \&nbsp; 这个转义字符
