### ISSUE TITLE
How to concat JS files

### ISSUE THREAD

**Issue by macphersonj** [chenzhutian/hexo-all-minifier#17]
Is it possible to concatenate JS into one file?

**Comment by alen12345** [comment]
I agree that the support to concat js and css files should be added optionally.

**Comment by stephencroberts** [comment]
@chenzhutian Would you be interested in a PR for this feature? I'm interested in concatenating JS and CSS as well and haven't found anything for hexo yet. This could be a good home for that feature.

**Comment by chenzhutian** [comment]
Yep I also want this feature while keeping the plugin light weight.
But I'm currently a little bit busy to do this work. I plan to implement this feature in Oct.
PRs are welcomed.

**Comment by chenzhutian** [comment]
@macphersonj @alen12345 @stephencroberts 
I have implemented a new feature to concat the Js scripts.
Please have a try the latest version v0.4.0.
The Js_concator is default to disable. You have to enable it manually.

**Comment by chenzhutian** [comment]
Close for inactivate
