### ISSUE TITLE
html_minifier makes inline code disappear

### ISSUE THREAD

**Issue by starbit** [chenzhutian/hexo-all-minifier#2]
Hi,

I installed this plugin and enabled the html_minifier, and all the code blocks in markdown disappeared after rendering and minifying. Then I disabled it, everything rendered fine.

So I wonder is it a bug of this plugin or hexo-html-minifier?

Here's my environment:
- OS X 10.11.2
- node 4.1.2
- hexo-all-minifier 0.0.11
- hexo-renderer-marked 0.2.8

**Comment by unhealthy** [comment]
HI, sorry for response lately because I'm still on Chinese New year holiday. I'll try to figure it out ASAP. Thanks for your feedback.

**Comment by unhealthy** [comment]
Hi, I can not repeat your case. The inline code and code block is all fine in my hexo-blog. Can you provide more detail? For example, your theme&config and so on.

**Comment by starbit** [comment]
Zhutian, I sent you a request on Google Talk and I think it might be better we talk through IM.

**Comment by chenzhutian** [comment]
close for inactive
