### ISSUE TITLE
js minifier makes code disappear

### ISSUE THREAD

**Issue by rollemira** [chenzhutian/hexo-all-minifier#29]
Seems like when enabling js minifications it just errors and produces a blank file.

**Comment by chenzhutian** [comment]
Can you provide a minimal repo to reproduce the bug? Because it works fine on my site..
Currently I will add some exception handler.

**Comment by chenzhutian** [comment]
I have published a new version.  Please have a try

**Comment by chenzhutian** [comment]
v0.2.5 is released to fix the uglify problem #30 
please have a try
