### ISSUE TITLE
Can I run this plugin only during generate command and not on serve ?

### ISSUE THREAD

**Issue by naveensky** [chenzhutian/hexo-all-minifier#40]
Currently, the minify instructions are run everytime I run `hexo generate` and `hexo server`

Is there a way I can disable this command and run only during `hexo generate` command?

**Comment by MZIchenjl** [comment]
set node NODE_ENV to be `development` may works

**Comment by chenzhutian** [comment]
Thanks @MZIchenjl  gave the solution!
