### ISSUE TITLE
slient:false end up with no info output as usual

### ISSUE THREAD

**Issue by wafer-li** [chenzhutian/hexo-all-minifier#46]
See the [log](https://travis-ci.org/wafer-li/wafer-li.github.io/jobs/329159405#L623)

And the related config [file](https://github.com/wafer-li/wafer-li.github.io/blob/281425a49b42bad7d6162765a3fee7556d192532/source/_data/next.yml#L135)

Only the 

```
bunyan usage error: /home/travis/build/wafer-li/wafer-li.github.io/node_modules/bluebird/js/release/util.js:16: attempt to log with an unbound log method: `this` is:
```
happened.

**Comment by wafer-li** [comment]
Although everything seems normal and works fine.

Buti I still concern about the error message and the weird behaviors

**Comment by dreamcreator108** [comment]
I have the same issue. The only difference is that my nodejs version is 8.9.4.

**Comment by chenzhutian** [comment]
@wafer-li @dreamcreator108  please try the latest version v0.5.2.
The error should be fixed

**Comment by dreamcreator108** [comment]
@chenzhutian There is no error in output anymore, thank you!
