### ISSUE TITLE
东西很好，但是开启后跑hexo server会非常慢

### ISSUE THREAD

**Issue by think2cat** [chenzhutian/hexo-all-minifier#55]
每次本地编辑都要先关掉，生成html时再打开
有没开关参数可以解决这个问题

**Comment by chenzhutian** [comment]
就是要开发模式下不启用么？

**Comment by think2cat** [comment]
是，我刚从wordpress换到hexo，新手，也不知道用的方法对不对
我是本地开hexo s进行编辑，然后再hexo g -d生成和提交
感觉当server时可以不用时刻去优化，而在生成时再进行优化

**Comment by chenzhutian** [comment]
ok,我看看能不能判断一下

**Comment by chenzhutian** [comment]
我发现我以及设置了开发者模式不启动，你可能得自己设置一下环境变量, 可以在npm script里加
windows 下是"set NODE_ENV=development&& hexo server" （注意没有空格在`&&`前面）
max or linux下是 "NODE_ENV=development hexo server"
