### ISSUE TITLE
Erron on install hexo-all-minifier

### ISSUE THREAD

**Issue by jonasmarco** [chenzhutian/hexo-all-minifier#58]
I'm trying to install hexo all minifier on my project, so when a run the npm install, I'm receiving some errors, can u help me?

![Image of Error!](https://i.imgur.com/SGKzxzY.png)

**Comment by chenzhutian** [comment]
So what's your node version and OS information?

**Comment by jonasmarco** [comment]
Node 10.0.0 on Debian 9 Stretch

**Comment by jonasmarco** [comment]
@chenzhutian any return?

**Comment by chenzhutian** [comment]
Sorry for the late reply.
Please see this https://docs.npmjs.com/getting-started/fixing-npm-permissions
More discussion please see this issue https://github.com/developit/preact-cli/issues/191
@jonasmarco
