### ISSUE TITLE
压缩后出现大小写变化，从而导致打赏button失效

### ISSUE THREAD

**Issue by Lruihao** [chenzhutian/hexo-all-minifier#64]
[![QQ截图20180823110150.png](https://i.loli.net/2018/08/23/5b7e25260f931.png)](https://i.loli.net/2018/08/23/5b7e25260f931.png)

红框处应为"QR"

**Comment by Lruihao** [comment]
该问题已解决，打开reward.swig修改引号为转义字符就OK，具体见[传送门](https://lruihao.cn/bugs.html)

**Comment by chenzhutian** [comment]
OK
传送门那个好炫
