### ISSUE TITLE
Run only when generating 

### ISSUE THREAD

**Issue by reyemtm** [chenzhutian/hexo-all-minifier#65]
Here is a working line of code to add to index.js to run the minifier only when generating the site, not when serving.

    if (process.argv.indexOf('server') > -1 || process.argv.indexOf('s') > -1 || process.argv.indexOf('serve') > -1) 
    {
      return;
    }

**Comment by chenzhutian** [comment]
Ok 

PR is welcome.
Also you can set the ENV to `development` to enable minifier.

```
const isEnabled = process.env.NODE_ENV !== 'development'
  && (hexo.config.hasOwnProperty('all_minifier') === false || hexo.config.all_minifier === true);
```
