### ISSUE TITLE
Didn't install

### ISSUE THREAD

**Issue by dcromster** [chenzhutian/hexo-all-minifier#72]
ubuntu@investor_cab:~/blog$ npm install hexo-all-minifier --save
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> gifsicle@3.0.4 postinstall /home/ubuntu/blog/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /home/ubuntu/blog/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> mozjpeg@5.0.0 postinstall /home/ubuntu/blog/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /home/ubuntu/blog/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@4.0.0 postinstall /home/ubuntu/blog/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/home/ubuntu/blog/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/ubuntu/blog/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-12-18T13_40_32_962Z-debug.log

Linux Ubuntu 18.04

**Comment by wzzxx7** [comment]
I met the same problem

![image](https://user-images.githubusercontent.com/38744714/80118680-53d3f600-85bb-11ea-9bc9-32db6b070350.png)

**Comment by grayguest** [comment]
install libtool automake autoconf nasm

**Comment by KumaNNN** [comment]
```
npm install hexo-all-minifier --save --ignore-scripts
```

**Comment by chenzhutian** [comment]
for the problem, please check this issue
https://github.com/chenzhutian/hexo-all-minifier/issues/101
